PracticaEntity/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PracticaEntity.Models
{
    [Table("dept")]
    public class Departamento
    {
        [Key]
        [Column("dept_no")]
        public int Numero { get; set; }
        [Column("dnombre")]
        public String Nombre { get; set; }
        [Column("loc")]
        public String Localidad { get; set; }
    }
}

PracticaEntity/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaEntity.Models;
using PracticaEntity.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PracticaEntity.Controllers
{
    public class DepartamentosController : Controller
    {
        private RepositoryDepartamento repo;

        public DepartamentosController(RepositoryDepartamento repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Departamento> departamentos = this.repo.GetDepartamentos();
            return View(departamentos);
        }
    }
}

PracticaEntity/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PracticaEntity.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PracticaEntity/Views/Departamentos/Index.cshtml
@model List<Departamento>
<h1>Departamentos EF</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Localidad</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Departamento dept in Model)
        {
            <tr>
                <td>@dept.Numero</td>
                <td>@dept.Nombre</td>
                <td>@dept.Localidad</td>
            </tr>
        }
    </tbody>
</table>

PracticaEntity/Views/Home/Index.cshtml
<h1>Index de Home</h1>

PracticaEntity/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Proyecto MVC</title>

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/navbar-top-fixed.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Departamentos">Departamentos</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main class="container">
        <div class="bg-light p-5 rounded">
            @RenderBody()
        </div>
    </main>

    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @*@RenderSection("scripts", false)*@
</body>
</html>